name: Pulumi
on:
  pull_request:
    branches:
      - dev
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: npm install
      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: HuckStream/Pipeline/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
